// Generated by tools/build-sw.mjs — do not edit by hand.
// Offline-first service worker: precaches the whole game, serves it from
// cache, and swaps to a new cache when the game is updated.
const VERSION = '0e0417fff583';
const CACHE = 'pan-' + VERSION;
const ASSETS = [
  "./",
  "./index.html",
  "./manifest.webmanifest",
  "./css/style.css",
  "./js/audio.js",
  "./js/bots.js",
  "./js/data/bots.js",
  "./js/data/events.js",
  "./js/data/gear.js",
  "./js/data/items.js",
  "./js/data/minerals.js",
  "./js/data/quests.js",
  "./js/data/rarity.js",
  "./js/data/shores.js",
  "./js/game.js",
  "./js/loot.js",
  "./js/main.js",
  "./js/polyfills.js",
  "./js/progression.js",
  "./js/render/character.js",
  "./js/render/icons.js",
  "./js/render/scene.js",
  "./js/state.js",
  "./js/stats.js",
  "./js/ui/icons.js",
  "./js/ui/panels.js",
  "./js/ui/ui.js",
  "./js/util.js",
  "./js/worldclock.js",
  "./assets/fonts/fredoka.woff2",
  "./icons/apple-touch-icon.png",
  "./icons/favicon-32.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/maskable-512.png"
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('pan-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  if (req.mode === 'navigate') {
    // pages: network first (so updates show up) with a quick fallback to
    // the cached copy when offline or on a slow connection
    const network = fetch(req).then((res) => {
      if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put('./', copy)).catch(() => {}); }
      return res;
    });
    const cached = () => caches.match('./', { ignoreSearch: true });
    const timeout = new Promise((resolve) => setTimeout(resolve, 2500)).then(cached);
    event.respondWith(
      Promise.race([network.catch(cached), timeout.then((r) => r || network)])
        .then((r) => r || network)
        .catch(cached),
    );
    return;
  }
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {}); }
      return res;
    })),
  );
});
