// Regenerates sw.js with the full precache list and a content-hash version.
// Run after changing any game file:  node tools/build-sw.mjs
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

const root = path.join(path.dirname(new URL(import.meta.url).pathname), '..');
const include = ['index.html', 'manifest.webmanifest', 'css', 'js', 'assets', 'icons'];
const skip = new Set(['icons/preview.png', 'assets/fonts/OFL.txt']);
const files = [];
function walk(rel) {
  const abs = path.join(root, rel);
  const st = fs.statSync(abs);
  if (st.isDirectory()) for (const f of fs.readdirSync(abs).sort()) walk(path.posix.join(rel, f));
  else if (!skip.has(rel)) files.push(rel);
}
include.forEach(walk);
const hash = crypto.createHash('sha256');
for (const f of files) hash.update(f).update(fs.readFileSync(path.join(root, f)));
const version = hash.digest('hex').slice(0, 12);
const list = ['./', ...files.map((f) => './' + f)];

const sw = `// Generated by tools/build-sw.mjs — do not edit by hand.
// Offline-first service worker: precaches the whole game, serves it from
// cache, and swaps to a new cache when the game is updated.
const VERSION = '${version}';
const CACHE = 'pan-' + VERSION;
const ASSETS = ${JSON.stringify(list, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('pan-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  if (req.mode === 'navigate') {
    // pages: network first (so updates show up) with a quick fallback to
    // the cached copy when offline or on a slow connection
    const network = fetch(req).then((res) => {
      if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put('./', copy)).catch(() => {}); }
      return res;
    });
    const cached = () => caches.match('./', { ignoreSearch: true });
    const timeout = new Promise((resolve) => setTimeout(resolve, 2500)).then(cached);
    event.respondWith(
      Promise.race([network.catch(cached), timeout.then((r) => r || network)])
        .then((r) => r || network)
        .catch(cached),
    );
    return;
  }
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {}); }
      return res;
    })),
  );
});
`;
fs.writeFileSync(path.join(root, 'sw.js'), sw);
console.log(`sw.js written: ${list.length} assets, version ${version}`);
